<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('country_time_zones', function (Blueprint $table) {
            $table->id();
            $table->string('country')->nullable();
            $table->string('time_zone')->unique()->nullable();
            $table->string('utc_offset')->nullable();
            $table->boolean('status')->default(1)->comment('1 => active, 0=> inactive');
        });

        DB::table('country_time_zones')->insert(
            [
                ['country' => 'Afghanistan', 'time_zone' => 'Asia/Kabul', 'utc_offset' => '4.50'],
                ['country' => 'Albania', 'time_zone' => 'Europe/Tirane', 'utc_offset' => '1.00'],
                ['country' => 'Algeria', 'time_zone' => 'Africa/Algiers', 'utc_offset' => '1.00'],
                ['country' => 'Andorra', 'time_zone' => 'Europe/Andorra', 'utc_offset' => '1.00'],
                ['country' => 'Angola', 'time_zone' => 'Africa/Luanda', 'utc_offset' => '1.00'],
                ['country' => 'Antigua and Barbuda', 'time_zone' => 'America/Antigua', 'utc_offset' => '-4.00'],
                ['country' => 'Argentina', 'time_zone' => 'America/Argentina/Buenos_Aires', 'utc_offset' => '-3.00'],
                ['country' => 'Armenia', 'time_zone' => 'Asia/Yerevan', 'utc_offset' => '4.00'],
                ['country' => 'Australia', 'time_zone' => 'Australia/Sydney', 'utc_offset' => '10.00'],
                ['country' => 'Austria', 'time_zone' => 'Europe/Vienna', 'utc_offset' => '1.00'],
                ['country' => 'Azerbaijan', 'time_zone' => 'Asia/Baku', 'utc_offset' => '4.00'],
                ['country' => 'Bahamas', 'time_zone' => 'America/Nassau', 'utc_offset' => '-5.00'],
                ['country' => 'Bahrain', 'time_zone' => 'Asia/Bahrain', 'utc_offset' => '3.00'],
                ['country' => 'Bangladesh', 'time_zone' => 'Asia/Dhaka', 'utc_offset' => '6.00'],
                ['country' => 'Barbados', 'time_zone' => 'America/Barbados', 'utc_offset' => '-4.00'],
                ['country' => 'Belarus', 'time_zone' => 'Europe/Minsk', 'utc_offset' => '3.00'],
                ['country' => 'Belgium', 'time_zone' => 'Europe/Brussels', 'utc_offset' => '1.00'],
                ['country' => 'Belize', 'time_zone' => 'America/Belize', 'utc_offset' => '-6.00'],
                ['country' => 'Benin', 'time_zone' => 'Africa/Porto-Novo', 'utc_offset' => '1.00'],
                ['country' => 'Bhutan', 'time_zone' => 'Asia/Thimphu', 'utc_offset' => '6.00'],
                ['country' => 'Bolivia', 'time_zone' => 'America/La_Paz', 'utc_offset' => '-4.00'],
                ['country' => 'Bosnia and Herzegovina', 'time_zone' => 'Europe/Sarajevo', 'utc_offset' => '1.00'],
                ['country' => 'Botswana', 'time_zone' => 'Africa/Gaborone', 'utc_offset' => '2.00'],
                ['country' => 'Brazil', 'time_zone' => 'America/Sao_Paulo', 'utc_offset' => '-3.00'],
                ['country' => 'Brunei', 'time_zone' => 'Asia/Brunei', 'utc_offset' => '8.00'],
                ['country' => 'Bulgaria', 'time_zone' => 'Europe/Sofia', 'utc_offset' => '2.00'],
                ['country' => 'Burkina Faso', 'time_zone' => 'Africa/Ouagadougou', 'utc_offset' => '0.00'],
                ['country' => 'Burundi', 'time_zone' => 'Africa/Bujumbura', 'utc_offset' => '2.00'],
                ['country' => 'Cambodia', 'time_zone' => 'Asia/Phnom_Penh', 'utc_offset' => '7.00'],
                ['country' => 'Cameroon', 'time_zone' => 'Africa/Douala', 'utc_offset' => '1.00'],
                ['country' => 'Canada', 'time_zone' => 'America/Toronto', 'utc_offset' => '-5.00'],
                ['country' => 'Cape Verde', 'time_zone' => 'Atlantic/Cape_Verde', 'utc_offset' => '-1.00'],
                ['country' => 'Central African Republic', 'time_zone' => 'Africa/Bangui', 'utc_offset' => '1.00'],
                ['country' => 'Chad', 'time_zone' => 'Africa/Ndjamena', 'utc_offset' => '1.00'],
                ['country' => 'Chile', 'time_zone' => 'America/Santiago', 'utc_offset' => '-3.00'],
                ['country' => 'China', 'time_zone' => 'Asia/Shanghai', 'utc_offset' => '8.00'],
                ['country' => 'Colombia', 'time_zone' => 'America/Bogota', 'utc_offset' => '-5.00'],
                ['country' => 'Comoros', 'time_zone' => 'Indian/Comoro', 'utc_offset' => '3.00'],
                ['country' => 'Congo', 'time_zone' => 'Africa/Brazzaville', 'utc_offset' => '1.00'],
                ['country' => 'Costa Rica', 'time_zone' => 'America/Costa_Rica', 'utc_offset' => '-6.00'],
                ['country' => 'Croatia', 'time_zone' => 'Europe/Zagreb', 'utc_offset' => '1.00'],
                ['country' => 'Cuba', 'time_zone' => 'America/Havana', 'utc_offset' => '-5.00'],
                ['country' => 'Cyprus', 'time_zone' => 'Asia/Nicosia', 'utc_offset' => '2.00'],
                ['country' => 'Czech Republic', 'time_zone' => 'Europe/Prague', 'utc_offset' => '1.00'],
                ['country' => 'Denmark', 'time_zone' => 'Europe/Copenhagen', 'utc_offset' => '1.00'],
                ['country' => 'Djibouti', 'time_zone' => 'Africa/Djibouti', 'utc_offset' => '3.00'],
                ['country' => 'Dominica', 'time_zone' => 'America/Dominica', 'utc_offset' => '-4.00'],
                ['country' => 'Dominican Republic', 'time_zone' => 'America/Santo_Domingo', 'utc_offset' => '-4.00'],
                ['country' => 'East Timor', 'time_zone' => 'Asia/Dili', 'utc_offset' => '9.00'],
                ['country' => 'Ecuador', 'time_zone' => 'America/Guayaquil', 'utc_offset' => '-5.00'],
                ['country' => 'Egypt', 'time_zone' => 'Africa/Cairo', 'utc_offset' => '2.00'],
                ['country' => 'El Salvador', 'time_zone' => 'America/El_Salvador', 'utc_offset' => '-6.00'],
                ['country' => 'Equatorial Guinea', 'time_zone' => 'Africa/Malabo', 'utc_offset' => '1.00'],
                ['country' => 'Eritrea', 'time_zone' => 'Africa/Asmara', 'utc_offset' => '3.00'],
                ['country' => 'Estonia', 'time_zone' => 'Europe/Tallinn', 'utc_offset' => '2.00'],
                ['country' => 'Eswatini', 'time_zone' => 'Africa/Mbabane', 'utc_offset' => '2.00'],
                ['country' => 'Ethiopia', 'time_zone' => 'Africa/Addis_Ababa', 'utc_offset' => '3.00'],
                ['country' => 'Fiji', 'time_zone' => 'Pacific/Fiji', 'utc_offset' => '12.00'],
                ['country' => 'Finland', 'time_zone' => 'Europe/Helsinki', 'utc_offset' => '2.00'],
                ['country' => 'France', 'time_zone' => 'Europe/Paris', 'utc_offset' => '1.00'],
                ['country' => 'Gabon', 'time_zone' => 'Africa/Libreville', 'utc_offset' => '1.00'],
                ['country' => 'Gambia', 'time_zone' => 'Africa/Banjul', 'utc_offset' => '0.00'],
                ['country' => 'Georgia', 'time_zone' => 'Asia/Tbilisi', 'utc_offset' => '4.00'],
                ['country' => 'Germany', 'time_zone' => 'Europe/Berlin', 'utc_offset' => '1.00'],
                ['country' => 'Ghana', 'time_zone' => 'Africa/Accra', 'utc_offset' => '0.00'],
                ['country' => 'Greece', 'time_zone' => 'Europe/Athens', 'utc_offset' => '2.00'],
                ['country' => 'Grenada', 'time_zone' => 'America/Grenada', 'utc_offset' => '-4.00'],
                ['country' => 'Guatemala', 'time_zone' => 'America/Guatemala', 'utc_offset' => '-6.00'],
                ['country' => 'Guinea', 'time_zone' => 'Africa/Conakry', 'utc_offset' => '0.00'],
                ['country' => 'Guinea-Bissau', 'time_zone' => 'Africa/Bissau', 'utc_offset' => '0.00'],
                ['country' => 'Guyana', 'time_zone' => 'America/Guyana', 'utc_offset' => '-4.00'],
                ['country' => 'Haiti', 'time_zone' => 'America/Port-au-Prince', 'utc_offset' => '-5.00'],
                ['country' => 'Honduras', 'time_zone' => 'America/Tegucigalpa', 'utc_offset' => '-6.00'],
                ['country' => 'Hungary', 'time_zone' => 'Europe/Budapest', 'utc_offset' => '1.00'],
                ['country' => 'Iceland', 'time_zone' => 'Atlantic/Reykjavik', 'utc_offset' => '0.00'],
                ['country' => 'India', 'time_zone' => 'Asia/Kolkata', 'utc_offset' => '5.50'],
                ['country' => 'Indonesia', 'time_zone' => 'Asia/Jakarta', 'utc_offset' => '7.00'],
                ['country' => 'Iran', 'time_zone' => 'Asia/Tehran', 'utc_offset' => '3.50'],
                ['country' => 'Iraq', 'time_zone' => 'Asia/Baghdad', 'utc_offset' => '3.00'],
                ['country' => 'Ireland', 'time_zone' => 'Europe/Dublin', 'utc_offset' => '0.00'],
                ['country' => 'Israel', 'time_zone' => 'Asia/Jerusalem', 'utc_offset' => '2.00'],
                ['country' => 'Italy', 'time_zone' => 'Europe/Rome', 'utc_offset' => '1.00'],
                ['country' => 'Jamaica', 'time_zone' => 'America/Jamaica', 'utc_offset' => '-5.00'],
                ['country' => 'Japan', 'time_zone' => 'Asia/Tokyo', 'utc_offset' => '9.00'],
                ['country' => 'Jordan', 'time_zone' => 'Asia/Amman', 'utc_offset' => '2.00'],
                ['country' => 'Kazakhstan', 'time_zone' => 'Asia/Almaty', 'utc_offset' => '6.00'],
                ['country' => 'Kenya', 'time_zone' => 'Africa/Nairobi', 'utc_offset' => '3.00'],
                ['country' => 'Kiribati', 'time_zone' => 'Pacific/Tarawa', 'utc_offset' => '12.00'],
                ['country' => 'Kuwait', 'time_zone' => 'Asia/Kuwait', 'utc_offset' => '3.00'],
                ['country' => 'Kyrgyzstan', 'time_zone' => 'Asia/Bishkek', 'utc_offset' => '6.00'],
                ['country' => 'Laos', 'time_zone' => 'Asia/Vientiane', 'utc_offset' => '7.00'],
                ['country' => 'Latvia', 'time_zone' => 'Europe/Riga', 'utc_offset' => '2.00'],
                ['country' => 'Lebanon', 'time_zone' => 'Asia/Beirut', 'utc_offset' => '2.00'],
                ['country' => 'Lesotho', 'time_zone' => 'Africa/Maseru', 'utc_offset' => '2.00'],
                ['country' => 'Liberia', 'time_zone' => 'Africa/Monrovia', 'utc_offset' => '0.00'],
                ['country' => 'Libya', 'time_zone' => 'Africa/Tripoli', 'utc_offset' => '2.00'],
                ['country' => 'Liechtenstein', 'time_zone' => 'Europe/Vaduz', 'utc_offset' => '1.00'],
                ['country' => 'Lithuania', 'time_zone' => 'Europe/Vilnius', 'utc_offset' => '2.00'],
                ['country' => 'Luxembourg', 'time_zone' => 'Europe/Luxembourg', 'utc_offset' => '1.00'],
                ['country' => 'Madagascar', 'time_zone' => 'Indian/Antananarivo', 'utc_offset' => '3.00'],
                ['country' => 'Malawi', 'time_zone' => 'Africa/Blantyre', 'utc_offset' => '2.00'],
                ['country' => 'Malaysia', 'time_zone' => 'Asia/Kuala_Lumpur', 'utc_offset' => '8.00'],
                ['country' => 'Maldives', 'time_zone' => 'Indian/Maldives', 'utc_offset' => '5.00'],
                ['country' => 'Mali', 'time_zone' => 'Africa/Bamako', 'utc_offset' => 0.00],
                ['country' => 'Malta', 'time_zone' => 'Europe/Malta', 'utc_offset' => 1.00],
                ['country' => 'Marshall Islands', 'time_zone' => 'Pacific/Majuro', 'utc_offset' => 12.00],
                ['country' => 'Mauritania', 'time_zone' => 'Africa/Nouakchott', 'utc_offset' => 0.00],
                ['country' => 'Mauritius', 'time_zone' => 'Indian/Mauritius', 'utc_offset' => 4.00],
                ['country' => 'Mexico', 'time_zone' => 'America/Mexico_City', 'utc_offset' => -6.00],
                ['country' => 'Micronesia', 'time_zone' => 'Pacific/Pohnpei', 'utc_offset' => 11.00],
                ['country' => 'Moldova', 'time_zone' => 'Europe/Chisinau', 'utc_offset' => 2.00],
                ['country' => 'Monaco', 'time_zone' => 'Europe/Monaco', 'utc_offset' => 1.00],
                ['country' => 'Mongolia', 'time_zone' => 'Asia/Ulaanbaatar', 'utc_offset' => 8.00],
                ['country' => 'Montenegro', 'time_zone' => 'Europe/Podgorica', 'utc_offset' => 1.00],
                ['country' => 'Morocco', 'time_zone' => 'Africa/Casablanca', 'utc_offset' => 1.00],
                ['country' => 'Mozambique', 'time_zone' => 'Africa/Maputo', 'utc_offset' => 2.00],
                ['country' => 'Myanmar', 'time_zone' => 'Asia/Yangon', 'utc_offset' => 6.50],
                ['country' => 'Namibia', 'time_zone' => 'Africa/Windhoek', 'utc_offset' => 2.00],
                ['country' => 'Nauru', 'time_zone' => 'Pacific/Nauru', 'utc_offset' => 12.00],
                ['country' => 'Nepal', 'time_zone' => 'Asia/Kathmandu', 'utc_offset' => 5.75],
                ['country' => 'Netherlands', 'time_zone' => 'Europe/Amsterdam', 'utc_offset' => 1.00],
                ['country' => 'New Zealand', 'time_zone' => 'Pacific/Auckland', 'utc_offset' => 12.00],
                ['country' => 'Nicaragua', 'time_zone' => 'America/Managua', 'utc_offset' => -6.00],
                ['country' => 'Niger', 'time_zone' => 'Africa/Niamey', 'utc_offset' => 1.00],
                ['country' => 'Nigeria', 'time_zone' => 'Africa/Lagos', 'utc_offset' => 1.00],
                ['country' => 'North Korea', 'time_zone' => 'Asia/Pyongyang', 'utc_offset' => 9.00],
                ['country' => 'North Macedonia', 'time_zone' => 'Europe/Skopje', 'utc_offset' => 1.00],
                ['country' => 'Norway', 'time_zone' => 'Europe/Oslo', 'utc_offset' => 1.00],
                ['country' => 'Oman', 'time_zone' => 'Asia/Muscat', 'utc_offset' => 4.00],
                ['country' => 'Pakistan', 'time_zone' => 'Asia/Karachi', 'utc_offset' => 5.00],
                ['country' => 'Palau', 'time_zone' => 'Pacific/Palau', 'utc_offset' => 9.00],
                ['country' => 'Palestine', 'time_zone' => 'Asia/Gaza', 'utc_offset' => 2.00],
                ['country' => 'Panama', 'time_zone' => 'America/Panama', 'utc_offset' => -5.00],
                ['country' => 'Papua New Guinea', 'time_zone' => 'Pacific/Port_Moresby', 'utc_offset' => 10.00],
                ['country' => 'Paraguay', 'time_zone' => 'America/Asuncion', 'utc_offset' => -4.00],
                ['country' => 'Peru', 'time_zone' => 'America/Lima', 'utc_offset' => -5.00],
                ['country' => 'Philippines', 'time_zone' => 'Asia/Manila', 'utc_offset' => 8.00],
                ['country' => 'Poland', 'time_zone' => 'Europe/Warsaw', 'utc_offset' => 1.00],
                ['country' => 'Portugal', 'time_zone' => 'Europe/Lisbon', 'utc_offset' => 0.00],
                ['country' => 'Qatar', 'time_zone' => 'Asia/Qatar', 'utc_offset' => 3.00],
                ['country' => 'Romania', 'time_zone' => 'Europe/Bucharest', 'utc_offset' => 2.00],
                ['country' => 'Russia', 'time_zone' => 'Europe/Moscow', 'utc_offset' => 3.00],
                ['country' => 'Rwanda', 'time_zone' => 'Africa/Kigali', 'utc_offset' => 2.00],
                ['country' => 'Saint Kitts and Nevis', 'time_zone' => 'America/St_Kitts', 'utc_offset' => -4.00],
                ['country' => 'Saint Lucia', 'time_zone' => 'America/St_Lucia', 'utc_offset' => -4.00],
                ['country' => 'Saint Vincent and the Grenadines', 'time_zone' => 'America/St_Vincent', 'utc_offset' => -4.00],
                ['country' => 'Samoa', 'time_zone' => 'Pacific/Apia', 'utc_offset' => 13.00],
                ['country' => 'San Marino', 'time_zone' => 'Europe/San_Marino', 'utc_offset' => 1.00],
                ['country' => 'Sao Tome and Principe', 'time_zone' => 'Africa/Sao_Tome', 'utc_offset' => 0.00],
                ['country' => 'Saudi Arabia', 'time_zone' => 'Asia/Riyadh', 'utc_offset' => 3.00],
                ['country' => 'Senegal', 'time_zone' => 'Africa/Dakar', 'utc_offset' => 0.00],
                ['country' => 'Serbia', 'time_zone' => 'Europe/Belgrade', 'utc_offset' => 1.00],
                ['country' => 'Seychelles', 'time_zone' => 'Indian/Mahe', 'utc_offset' => 4.00],
                ['country' => 'Sierra Leone', 'time_zone' => 'Africa/Freetown', 'utc_offset' => 0.00],
                ['country' => 'Singapore', 'time_zone' => 'Asia/Singapore', 'utc_offset' => 8.00],
                ['country' => 'Slovakia', 'time_zone' => 'Europe/Bratislava', 'utc_offset' => 1.00],
                ['country' => 'Slovenia', 'time_zone' => 'Europe/Ljubljana', 'utc_offset' => 1.00],
                ['country' => 'Solomon Islands', 'time_zone' => 'Pacific/Guadalcanal', 'utc_offset' => 11.00],
                ['country' => 'Somalia', 'time_zone' => 'Africa/Mogadishu', 'utc_offset' => 3.00],
                ['country' => 'South Africa', 'time_zone' => 'Africa/Johannesburg', 'utc_offset' => 2.00],
                ['country' => 'South Korea', 'time_zone' => 'Asia/Seoul', 'utc_offset' => 9.00],
                ['country' => 'South Sudan', 'time_zone' => 'Africa/Juba', 'utc_offset' => 2.00],
                ['country' => 'Spain', 'time_zone' => 'Europe/Madrid', 'utc_offset' => 1.00],
                ['country' => 'Sri Lanka', 'time_zone' => 'Asia/Colombo', 'utc_offset' => 5.50],
                ['country' => 'Sudan', 'time_zone' => 'Africa/Khartoum', 'utc_offset' => 2.00],
                ['country' => 'Suriname', 'time_zone' => 'America/Paramaribo', 'utc_offset' => -3.00],
                ['country' => 'Sweden', 'time_zone' => 'Europe/Stockholm', 'utc_offset' => 1.00],
                ['country' => 'Switzerland', 'time_zone' => 'Europe/Zurich', 'utc_offset' => 1.00],
                ['country' => 'Syria', 'time_zone' => 'Asia/Damascus', 'utc_offset' => 2.00],
                ['country' => 'Taiwan', 'time_zone' => 'Asia/Taipei', 'utc_offset' => 8.00],
                ['country' => 'Tajikistan', 'time_zone' => 'Asia/Dushanbe', 'utc_offset' => 5.00],
                ['country' => 'Tanzania', 'time_zone' => 'Africa/Dar_es_Salaam', 'utc_offset' => 3.00],
                ['country' => 'Thailand', 'time_zone' => 'Asia/Bangkok', 'utc_offset' => 7.00],
                ['country' => 'Togo', 'time_zone' => 'Africa/Lome', 'utc_offset' => 0.00],
                ['country' => 'Tonga', 'time_zone' => 'Pacific/Tongatapu', 'utc_offset' => 13.00],
                ['country' => 'Trinidad and Tobago', 'time_zone' => 'America/Port_of_Spain', 'utc_offset' => -4.00],
                ['country' => 'Tunisia', 'time_zone' => 'Africa/Tunis', 'utc_offset' => 1.00],
                ['country' => 'Turkey', 'time_zone' => 'Europe/Istanbul', 'utc_offset' => 3.00],
                ['country' => 'Turkmenistan', 'time_zone' => 'Asia/Ashgabat', 'utc_offset' => 5.00],
                ['country' => 'Tuvalu', 'time_zone' => 'Pacific/Funafuti', 'utc_offset' => 12.00],
                ['country' => 'Uganda', 'time_zone' => 'Africa/Kampala', 'utc_offset' => 3.00],
                ['country' => 'Ukraine', 'time_zone' => 'Europe/Kiev', 'utc_offset' => 2.00],
                ['country' => 'United Arab Emirates', 'time_zone' => 'Asia/Dubai', 'utc_offset' => 4.00],
                ['country' => 'United Kingdom', 'time_zone' => 'Europe/London', 'utc_offset' => 0.00],
                ['country' => 'United States', 'time_zone' => 'America/New_York', 'utc_offset' => -5.00],
                ['country' => 'United States', 'time_zone' => 'America/Chicago', 'utc_offset' => -6.00],
                ['country' => 'United States', 'time_zone' => 'America/Denver', 'utc_offset' => -7.00],
                ['country' => 'United States', 'time_zone' => 'America/Los_Angeles', 'utc_offset' => -8.00],
                ['country' => 'Uruguay', 'time_zone' => 'America/Montevideo', 'utc_offset' => -3.00],
                ['country' => 'Uzbekistan', 'time_zone' => 'Asia/Tashkent', 'utc_offset' => 5.00],
                ['country' => 'Vanuatu', 'time_zone' => 'Pacific/Efate', 'utc_offset' => 11.00],
                ['country' => 'Vatican', 'time_zone' => 'Europe/Vatican', 'utc_offset' => 1.00],
                ['country' => 'Venezuela', 'time_zone' => 'America/Caracas', 'utc_offset' => -4.00],
                ['country' => 'Vietnam', 'time_zone' => 'Asia/Ho_Chi_Minh', 'utc_offset' => 7.00],
                ['country' => 'Yemen', 'time_zone' => 'Asia/Aden', 'utc_offset' => 3.00],
                ['country' => 'Zambia', 'time_zone' => 'Africa/Lusaka', 'utc_offset' => 2.00],
                ['country' => 'Zimbabwe', 'time_zone' => 'Africa/Harare', 'utc_offset' => 2.00],
            ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_time_zones');
    }
};
