name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          npm install
        working-directory: SarasAI-Repo-1/SARAS_AI_FRONTEND

      - name: Create Jest configuration
        run: |
          echo "module.exports = {
            transform: {
              '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
            },
            transformIgnorePatterns: [
              '/node_modules/(?!(axios)/)',
            ],
            moduleNameMapper: {
              '\\\\.(css|less|scss|sass)$': 'identity-obj-proxy',
            },
            testEnvironment: 'jsdom',
          };" > SarasAI-Repo-1/SARAS_AI_FRONTEND/jest.config.js

      - name: Create Babel configuration
        run: |
          echo '{
            "presets": ["@babel/preset-env", "@babel/preset-react"],
            "plugins": ["@babel/plugin-proposal-private-property-in-object"]
          }' > SarasAI-Repo-1/SARAS_AI_FRONTEND/.babelrc

      - name: Install Babel packages
        run: |
          npm install --save-dev babel-jest @babel/core @babel/preset-env @babel/preset-react @babel/plugin-proposal-private-property-in-object
        working-directory: SarasAI-Repo-1/SARAS_AI_FRONTEND
      - name: Run tests
        run: npm test
        working-directory: SSarasAI-Repo-1/SARAS_AI_FRONTEND

      - name: Lint code
        run: npm run lint
        working-directory: SarasAI-Repo-1/SARAS_AI_FRONTEND

      - name: Build frontend project
        run: npm run build
        working-directory: SarasAI-Repo-1/SARAS_AI_FRONTEND

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install backend dependencies
        run: composer install
        working-directory: backendapi

      # Azure Login
      - name: Azure Login
        run: |
          az login --use-device-code

      # Azure Docker Login
      - name: Azure Docker Login
        if: success()
        uses: azure/docker-login@v1
        with:
          login-server: sarasai.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image for frontend to ACR
      - name: Build and push Docker image for frontend
        if: success()
        run: |
          cd SarasAI-Repo-1/SARAS_AI_FRONTEND
          docker build . -t sarasai.azurecr.io/sarasaifrontend:${{ github.sha }}
          docker push sarasai.azurecr.io/sarasaifrontend:${{ github.sha }}

      # Build and push Docker image for backend to ACR
      - name: Build and push Docker image for backend
        if: success()
        run: |
          cd backendapi
          docker build . -t sarasai.azurecr.io/sarasaibackend:${{ github.sha }}
          docker push sarasai.azurecr.io/sarasaibackend:${{ github.sha }}

      # Deploy to Azure Container Apps (optional)
      # - name: Deploy frontend to Azure Container Apps
      #   if: success()
      #   run: |
      #     RESOURCE_GROUP=rg
      #     CONTAINER_APP_NAME=frontend
      #     ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
      #     IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/sarasaifrontend

      #     # Retry mechanism for deploying frontend to Azure Container Apps
      #     for i in {1..5}; do
      #       az containerapp update \
      #         --name $CONTAINER_APP_NAME \
      #         --resource-group $RESOURCE_GROUP \
      #         --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} && break || sleep 60
      #     done

      # - name: Deploy backend to Azure Container Apps
      #   if: success()
      #   run: |
      #     RESOURCE_GROUP=rg
      #     CONTAINER_APP_NAME=backend
      #     ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
      #     IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/sarasabackend

      #     # Retry mechanism for deploying backend to Azure Container Apps
      #     for i in {1..5}; do
      #       az containerapp update \
      #         --name $CONTAINER_APP_NAME \
      #         --resource-group $RESOURCE_GROUP \
      #         --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} && break || sleep 60
      #     done
